config/routes.rb
Rails.application.routes.draw do

root "guitars#search"

resources :guitars do
  collection do
    get :search
  end
end

resources :makers 

end

app/models/csv_importer.rb
# CsvImporter.import("some_file")
#
# importer = CsvImporter.new("some_file")
# importer.import
#
# CsvImporter.new("some_file").import

class CsvImporter
  def initialize(filename)
    @filename = filename
  end

  def import
    SmarterCSV.process(@filename).each do |row|
      Guitar.create(row)
    end
  end
end

app/models/guitar.rb
class Guitar < ActiveRecord::Base

  def self.search(make, query)
    where("make like :make AND :query >= serial_range_start AND :query <= serial_range_end", make: make, query: query)
  end

end

app/models/maker.rb
class Maker < ActiveRecord::Base
end

app/models/reverb_api_importer.rb
class ReverbApiImporter
  def initialize(query)
    @query = query
  end

  def import
    # This response is a page of 24 listings along with total, links, etc
    response = HTTParty.get("https://reverb.com/api/listings?query=#{@query}")
    parsed_json = JSON.parse(response)

    # This is an array of hashes (each hash represents a listing)
    listings = parsed_json["listings"]

    listings.each do |listing|
      Guitar.create(
        make: listing["make"],
        model: listing["model"],
        description: listing["description"]
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController

    PER_PAGE = 60


      before_filter :authenticate

      def authenticate
        authenticate_or_request_with_http_basic('Administration') do |username, password|
          username == 'admin' && password == '123'
        end
      end

    def index
      page_number = params[:page] ? params[:page].to_i : 1
      guitars_offset = PER_PAGE * (page_number - 1)
      @guitars   = Guitar.limit(PER_PAGE).offset(guitars_offset)
      @next_page  = page_number + 1 if @guitars.count == PER_PAGE
    end
  # [END index]

    # [START new_and_edit]
    def new
      @guitar = Guitar.new
      # render template: "new"
    end

    def edit
      @guitar = Guitar.find params[:id]
      @listings = get_reverb_listings(@guitar)
    end
    # [END new_and_edit]

    # [START show]
    def show
      @guitar = Guitar.find params[:id]
    end
    # [END show]

    # [START destroy]
    def destroy
      @guitar = Guitar.find params[:id]
      @guitar.destroy
      redirect_to guitars_path
    end
    # [END destroy]

    # [START update]
    def update
      @guitar = Guitar.find params[:id]

      if @guitar.update guitar_params
        flash[:success] = "Updated guitar"
        redirect_to guitars_path(@guitar)
      else
        render :edit
      end
    end
    # [END update]

    # [START create]
    def create
      @guitar = Guitar.new guitar_params

      if @guitar.save
        flash[:success] = "Added guitar"
        redirect_to guitars_path(@guitar)
      else
        render :new
      end
    end

    def search
      @guitar = Guitar.search(params[:make], params[:query]).first
      @listings = get_reverb_listings(@guitar)
    end

    private

    def guitar_params
      params.require(:guitar).permit(:make, :model, :description, :serial_range_start, :serial_range_end, :month,:year)
    end

    def get_reverb_listings(guitar)
      return [] unless guitar.present?
      # Fuzzy way
      # query = "#{@guitar.make} #{@guitar.model} #{@guitar.year}"
      # url = URI.escape("https://reverb.com/api/listings?query=#{query}&per_page=20")
      # Sturcutred way
      url = URI.escape("https://reverb.com/api/listings?make=#{guitar.make}&model=#{guitar.model}&year=#{guitar.year}&per_page=15")
      response = HTTParty.get(url)
      parsed_json = JSON.parse(response)
      parsed_json["listings"]
    end
    # [END create]
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController

  PER_PAGE = 20
  def index
    page_number = params[:page] ? params[:page].to_i : 1
    makers_offset = PER_PAGE * (page_number - 1)
    @makers  = Maker.limit(PER_PAGE).offset(makers_offset)
    @next_page  = page_number + 1 if @makers.count == PER_PAGE
  end
  # [END index]

  # [START new_and_edit]
  def new
    @maker = Maker.new
    # render template: "new"
  end

  def edit
    @maker = Maker.find params[:id]
  end
  # [END new_and_edit]

  # [START show]
  def show
    @maker = Maker.find params[:id]
  end
  # [END show]

  # [START destroy]
  def destroy
    @maker = Maker.find params[:id]
    @maker.destroy
    redirect_to makers_path
  end
  # [END destroy]

  # [START update]
  def update
    @maker = Maker.find params[:id]

    if @maker.update maker_params
      flash[:success] = "Updated maker"
      redirect_to makers_path(@maker)
    else
      render :edit
    end
  end
  # [END update]

  # [START create]
  def create
    @maker = Maker.new maker_params

    if @maker.save
      flash[:success] = "Added Maker"
      redirect_to makers_path(@maker)
    else
      render :new
    end
  end

  private

  def maker_params
    params.require(:maker).permit(:maker_name, :maker_url,:maker_image_url,:maker_serial_url, :maker_description)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/views/guitars/_reverb_listings.html.erb
<br>
<br>


<%= image_tag "reverb_logo.png", height: "33", width: "136" %>
<br>
<br>
<% listings.each do |listing| %>
  <%= link_to image_tag(listing["_links"]["photo"]["href"],:width => 120, :height => 120), listing["_links"]["web"]["href"] %>
<% end %>

app/views/guitars/edit.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h1>Edit Guitar</h1>

<%= render partial: "form" %>

<br>
<br>

<%= image_tag "reverb_logo.png", height: "38", width: "136" %>

<% @listings.each do |listing| %>
  <%= link_to image_tag(listing["_links"]["photo"]["href"],:width => 100, :height => 100), listing["_links"]["web"]["href"] %>
<% end %>

app/views/guitars/index.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h3>Guitar Database</h3>
<
<%= link_to new_guitar_path, class: "btn btn-success btn-sm" do %>
  <i class="glyphicon glyphicon-plus"></i>
  <span>Add Guitar</span>
<% end %>

<div>
  <%= form_tag search_guitars_path, method: :get do |form| %>
    <%= select_tag :make, options_for_select(Guitar.uniq.pluck(:make)) %>
    <%= text_field_tag :query %>
    <%= submit_tag "Search" %>
  <% end %>
</div>


<%# [START book_list] %>
<table class="table table-striped table-bordered">
<thead>
  <tr>
  <td>make</td>
  <td>Model</td>
  <td>description</td>
  <td>serial_range_start</td>
  <td>serial_range_end</td>
  <td>month</td>
  <td>year</td>
  <td></td>
  <td></td>
  <td></td>
</tr>
</thead>

<% @guitars.each do |guitar| %>
  <tr>
    <td><%= guitar.make %></td>
    <td><%= guitar.model %></td>
    <td><%= guitar.description %></td>
    <td><%= guitar.serial_range_start %></td>
    <td><%= guitar.serial_range_end %></td>
    <td><%= guitar.month %></td>
    <td><%= guitar.year %></td>

    <td><%= link_to "Edit", edit_guitar_path(guitar) %></td>
    <td><%= link_to "View", guitar_path(guitar) %></td>
    <td> <%= link_to "Delete", guitar_path(guitar), method: :delete  %> </td>
  </tr>
<% end %>
</table>

<% if @next_page %>
  <nav>
    <ul class="pager">
      <li><%= link_to "More", guitars_path(page: @next_page) %></li>
    </ul>
  </nav>
<% end %>
<%# [END book_list] %>


<% if @guitars.none? %>
  <p>No Guitars found.</p>
<% end %>

app/views/guitars/search.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<table class="table" >
<thead>
<tr>
  <%= link_to((image_tag 'date_your_guitar.png'), search_guitars_path) %>
</tr>
</thead>
  <tr>
    <td>Input Make / Model & Serial Number</td>
  </tr>
<tr>
  <td>

    <%= form_tag search_guitars_path, method: :get do |form| %>
    <%= select_tag :make, options_for_select(Maker.uniq.pluck(:maker_name)) %>
      <%= text_field_tag :query, params[:query] , placeholder: "L3456" %>
    <%= submit_tag "Search", class: "btn btn-success"  %>

  <% end %>
  </td>
</tr>
<tr>
</tr>

<% if @guitar %>

<tr>
  <td>
  <%= @guitar.make %> <%= @guitar.model%> was built in : <%= @guitar.year %>
  </td>
</tr>


<tr>
  <td>

Check out the following <%= @guitar.make %> guitars on Reverb from: <%= @guitar.year %>

<%= render "reverb_listings", listings: @listings %>
<% elsif params[:query] %>
  No results.
<% end %>
</td>
</tr>


</table>

app/views/guitars/show.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h3>guitars</h3>

<div class="media">
  <div class="media-body">
    <p><%= @guitar.make %>
    <%= @guitar.model %>> 
    <%= @guitar.description %>> &nbsp;
    <%= @guitar.serial_range_start %>> &nbsp;
    <%= @guitar.serial_range_end %>> &nbsp;
    <%= @guitar.month %>> &nbsp;
    <%= @guitar.year %>> &nbsp;

  </p>
  </div>
</div>

<div class="btn-group">
  <%= link_to edit_guitar_path(@guitar), class: "btn btn-primary btn-sm" do %>
    <i class="glyphicon glyphicon-edit"></i>
    <span>Edit Guitar</span>
  <% end %>
  <%= link_to guitar_path(@guitar), class: "btn btn-danger btn-sm", method: :delete do %>
    <i class="glyphicon glyphicon-trash"></i>
    <span>Delete Guitar</span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Date Your Guitar</title>
    <meta charset="utf-8">
    <meta name="viewset" content="width=device-width, initial-scale=1">

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>

  </head>
  <body>


    <div class="container">
      <% if flash.any? %>
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type %>"><%= message %></div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/makers/_form.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>


<% if @maker.errors.any? %>
  <div class="errors">
    <% @maker.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  </div>
<% end %>

<%# [START book_form] %>


<%= form_for @maker do |f| %>
<div class="form-group">
  <%= f.label :maker_name %>
  <%= f.text_field :maker_name, size: 30 %>
</div>
<div class="form-group">
  <%= f.label :maker_url %>
  <%= f.text_field :maker_url, size: 50 %>
</div>

  <div class="form-group">
  <%= f.label :maker_serial_url %>
  <%= f.text_field :maker_serial_url %>
  </div>
  <div class="form-group">
  <%= f.label :maker_image_url %>
  <%= f.text_field :maker_image_url %>
  </div>

<div class="form-group">
  <%= f.label :maker_description %>
  <%= f.text_area :maker_description, cols: 40, rows: 10 %>
</div>








  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>
<%# [END book_form] %>

app/views/makers/edit.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h1>Edit Maker</h1>

<%= render partial: "form" %>

app/views/makers/index.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h3>Makers</h3>

<%= link_to new_maker_path, class: "btn btn-success btn-sm" do %>
  <i class="glyphicon glyphicon-plus"></i>
  <span>Add Maker ( i.e. Rickenbacker)</span>
<% end %>


<%# [START book_list] %>
<table class="table table-striped table-bordered">
<thead>
  <tr>
  <td>maker</td>
  <td>maker_url</td>
  <td>maker_serial_url</td>
  <td>maker_image_url</td>
  <td>maker_description</td>
  <td></td>
  <td></td>
  <td></td>

  </tr>
</thead>

<% @makers.each do |maker| %>
  <tr>
    <td><%= maker.maker_name %></td>
    <td><%= maker.maker_url %></td>
    <td><%= maker.maker_serial_url %></td>
    <td><%= maker.maker_image_url %></td>
      <td><%= maker.maker_description %></td>

    <td><%= link_to "Edit", edit_maker_path(maker) %></td>
    <td><%= link_to "View", maker_path(maker) %></td>
    <td> <%= link_to "Delete", maker_path(maker), method: :delete  %> </td>
  </tr>
<% end %>
</table>

<% if @next_page %>
  <nav>
    <ul class="pager">
      <li><%= link_to "More", makers_path(page: @next_page) %></li>
    </ul>
  </nav>
<% end %>
<%# [END book_list] %>


<% if @makers.none? %>
  <p>No Makers found.</p>
<% end %>

app/views/makers/new.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h1>New Maker</h1>
<%= render partial: "form" %>

app/views/makers/show.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h3>Makers</h3>

<div class="media">
  <div class="media-body">
    <p><%= @maker.maker_name %></p>
  </div>
</div>